apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: criminal-wolverine-java-quarkus-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/criminal-wolverine-java-quarkus